# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: warehouse.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fwarehouse.proto\x12\twarehouse\" \n\x10WarehouseRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"\xeb\x01\n\x11WarehouseResponse\x12\x14\n\x0cwarehouse_id\x18\x01 \x01(\t\x12\x16\n\x0ewarehouse_name\x18\x02 \x01(\t\x12\x19\n\x11warehouse_address\x18\x03 \x01(\t\x12\x1d\n\x15warehouse_postal_code\x18\x04 \x01(\x05\x12\x16\n\x0ewarehouse_city\x18\x05 \x01(\t\x12\x19\n\x11warehouse_country\x18\x06 \x01(\t\x12\x11\n\ttimestamp\x18\x07 \x01(\t\x12(\n\x0cproduct_data\x18\x08 \x03(\x0b\x32\x12.warehouse.Product\"}\n\x07Product\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x14\n\x0cproduct_name\x18\x02 \x01(\t\x12\x18\n\x10product_category\x18\x03 \x01(\t\x12\x18\n\x10product_quantity\x18\x04 \x01(\x05\x12\x14\n\x0cproduct_unit\x18\x05 \x01(\t\"\x1e\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0cPingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xa5\x01\n\x10WarehouseService\x12O\n\x10getWarehouseData\x12\x1b.warehouse.WarehouseRequest\x1a\x1c.warehouse.WarehouseResponse\"\x00\x12@\n\x0bHealthCheck\x12\x16.warehouse.PingRequest\x1a\x17.warehouse.PingResponse\"\x00\x32O\n\x12HealthCheckService\x12\x39\n\x04Ping\x12\x16.warehouse.PingRequest\x1a\x17.warehouse.PingResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'warehouse_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_WAREHOUSEREQUEST']._serialized_start=30
  _globals['_WAREHOUSEREQUEST']._serialized_end=62
  _globals['_WAREHOUSERESPONSE']._serialized_start=65
  _globals['_WAREHOUSERESPONSE']._serialized_end=300
  _globals['_PRODUCT']._serialized_start=302
  _globals['_PRODUCT']._serialized_end=427
  _globals['_PINGREQUEST']._serialized_start=429
  _globals['_PINGREQUEST']._serialized_end=459
  _globals['_PINGRESPONSE']._serialized_start=461
  _globals['_PINGRESPONSE']._serialized_end=492
  _globals['_WAREHOUSESERVICE']._serialized_start=495
  _globals['_WAREHOUSESERVICE']._serialized_end=660
  _globals['_HEALTHCHECKSERVICE']._serialized_start=662
  _globals['_HEALTHCHECKSERVICE']._serialized_end=741
# @@protoc_insertion_point(module_scope)
